pluginGroup = com.shuzijun.leetcode
pluginName = LeetCode Editor
pluginVersion = 8.16

pluginSinceBuild = 251
pluginUntilBuild =
pluginDescription = doc/description.html

platformType = IU
platformVersion = 2025.1

# ,-Dide.browser.jcef.log.level=verbose,-Duser.language=en-US
runIdeJvmArgs = -Dfile.encoding=utf-8
